{
    'name': 'Clinic Core',
    'version': '17.0.1.0.0',
    'summary': 'Clinical Management System — Core Foundation',
    'description': 'Multi-company (HQ + 3 branches), ICD-10, security groups, clinic parameters.',
    'category': 'Health',
    'author': 'Clinic Dev',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/clinic_security.xml',
        'data/clinic_specialty_data.xml',
        'data/clinic_icd10_data.xml',
        'views/clinic_specialty_views.xml',
        'views/clinic_icd10_views.xml',
        'views/clinic_config_views.xml',
        'views/menu_views.xml',
    ],
    'demo': ['demo/clinic_core_demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
